import {
  RealmType,
  Item,
  ItemType,
  CultivationArt,
  ItemRarity,
  SectRank,
  SecretRealm,
  Recipe,
  Talent,
  Title,
  EncounterEvent,
  ExplorationLocation,
  Achievement,
  PetTemplate,
  PetSkill,
  LotteryPrize,
  EquipmentSlot,
  Shop,
  ShopType,
  ShopItem,
} from './types';

export const REALM_ORDER = [
  RealmType.QiRefining,
  RealmType.Foundation,
  RealmType.GoldenCore,
  RealmType.NascentSoul,
  RealmType.SpiritSevering,
  RealmType.VoidRefining,
  RealmType.ImmortalAscension,
];

export const REALM_DATA: Record<
  RealmType,
  {
    baseMaxHp: number;
    baseAttack: number;
    baseDefense: number;
    baseSpirit: number; // 神识
    basePhysique: number; // 体魄
    baseSpeed: number; // 速度
    maxExpBase: number;
  }
> = {
  [RealmType.QiRefining]: {
    baseMaxHp: 100,
    baseAttack: 10,
    baseDefense: 5,
    baseSpirit: 5,
    basePhysique: 10,
    baseSpeed: 10,
    maxExpBase: 100,
  },
  [RealmType.Foundation]: {
    baseMaxHp: 500,
    baseAttack: 50,
    baseDefense: 25,
    baseSpirit: 25,
    basePhysique: 50,
    baseSpeed: 30,
    maxExpBase: 1000,
  },
  [RealmType.GoldenCore]: {
    baseMaxHp: 2500,
    baseAttack: 200,
    baseDefense: 100,
    baseSpirit: 100,
    basePhysique: 200,
    baseSpeed: 50,
    maxExpBase: 5000,
  },
  [RealmType.NascentSoul]: {
    baseMaxHp: 10000,
    baseAttack: 1000,
    baseDefense: 500,
    baseSpirit: 500,
    basePhysique: 1000,
    baseSpeed: 100,
    maxExpBase: 25000,
  },
  [RealmType.SpiritSevering]: {
    baseMaxHp: 50000,
    baseAttack: 5000,
    baseDefense: 2500,
    baseSpirit: 2500,
    basePhysique: 5000,
    baseSpeed: 200,
    maxExpBase: 100000,
  },
  [RealmType.VoidRefining]: {
    baseMaxHp: 200000,
    baseAttack: 20000,
    baseDefense: 10000,
    baseSpirit: 10000,
    basePhysique: 20000,
    baseSpeed: 300,
    maxExpBase: 500000,
  },
  [RealmType.ImmortalAscension]: {
    baseMaxHp: 1000000,
    baseAttack: 100000,
    baseDefense: 50000,
    baseSpirit: 50000,
    basePhysique: 100000,
    baseSpeed: 500,
    maxExpBase: 9999999,
  },
};

export const RARITY_MULTIPLIERS: Record<ItemRarity, number> = {
  普通: 1,
  稀有: 1.5,
  传说: 2.5,
  仙品: 5.0,
};

export const CULTIVATION_ARTS: CultivationArt[] = [
  {
    id: 'art-basic-breath',
    name: '吐纳法',
    type: 'mental',
    description: '基础的呼吸吐纳之术，微弱提升修炼速度。',
    realmRequirement: RealmType.QiRefining,
    cost: 0,
    effects: { expRate: 0.1 },
  },
  {
    id: 'art-iron-skin',
    name: '铁皮功',
    type: 'body',
    description: '锤炼皮肉，使其坚如凡铁。永久提升防御。',
    realmRequirement: RealmType.QiRefining,
    cost: 50,
    effects: { defense: 5, hp: 20 },
  },
  {
    id: 'art-spirit-cloud',
    name: '云灵诀',
    type: 'mental',
    description: '云灵宗入门心法，吸纳灵气如云雾缭绕。',
    realmRequirement: RealmType.QiRefining,
    cost: 100,
    sectId: 'sect-cloud', // 云灵宗专属
    effects: { expRate: 0.25, attack: 5 },
  },
  {
    id: 'art-fiery-fist',
    name: '烈火拳',
    type: 'body',
    description: '将灵气转化为烈火附着于双拳。大幅提升攻击力。',
    realmRequirement: RealmType.Foundation,
    cost: 300,
    effects: { attack: 30 },
  },
  {
    id: 'art-jade-bone',
    name: '玉骨功',
    type: 'body',
    description: '锻骨如玉，百毒不侵。大幅提升气血与防御。',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    effects: { defense: 20, hp: 100 },
  },
  {
    id: 'art-pure-yang',
    name: '纯阳无极功',
    type: 'mental',
    description: '至刚至阳的高深心法，修炼速度极快。',
    realmRequirement: RealmType.GoldenCore,
    cost: 2000,
    effects: { expRate: 0.5, attack: 50 },
  },
  {
    id: 'art-thunder-sword',
    name: '天雷剑诀',
    type: 'body',
    description: '引九天神雷入剑，威力绝伦，若是肉身不够强横恐遭反噬。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3000,
    effects: { attack: 150 },
  },
  {
    id: 'art-immortal-life',
    name: '长生诀',
    type: 'mental',
    description: '上古木系神功，生生不息，气血悠长。',
    realmRequirement: RealmType.NascentSoul,
    cost: 8000,
    effects: { expRate: 0.6, hp: 2000 },
  },
  {
    id: 'art-void-body',
    name: '虚空霸体',
    type: 'body',
    description: '炼化虚空之力入体，肉身成圣。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 20000,
    effects: { defense: 500, attack: 500, hp: 5000 },
  },
  {
    id: 'art-wind-step',
    name: '御风步',
    type: 'body',
    description: '身法如风，行动迅捷。提升攻击和速度。',
    realmRequirement: RealmType.QiRefining,
    cost: 80,
    effects: { attack: 8 },
  },
  {
    id: 'art-water-mirror',
    name: '水镜心法',
    type: 'mental',
    description: '心如止水，明镜高悬。提升修炼速度和防御。',
    realmRequirement: RealmType.Foundation,
    cost: 400,
    effects: { expRate: 0.3, defense: 15 },
  },
  {
    id: 'art-earth-shield',
    name: '厚土护体',
    type: 'body',
    description: '引大地之力护体，防御力极强。',
    realmRequirement: RealmType.Foundation,
    cost: 600,
    effects: { defense: 40, hp: 150 },
  },
  {
    id: 'art-ice-soul',
    name: '冰心诀',
    type: 'mental',
    description: '心如寒冰，不为外物所动。大幅提升修炼速度。',
    realmRequirement: RealmType.GoldenCore,
    cost: 2500,
    effects: { expRate: 0.6, defense: 30 },
  },
  {
    id: 'art-dragon-fist',
    name: '龙拳',
    type: 'body',
    description: '拳如真龙，威力无穷。大幅提升攻击力。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3500,
    effects: { attack: 200 },
  },
  {
    id: 'art-phoenix-rebirth',
    name: '凤凰涅槃功',
    type: 'mental',
    description: '如凤凰涅槃，每次突破都能获得巨大提升。',
    realmRequirement: RealmType.NascentSoul,
    cost: 10000,
    effects: { expRate: 0.7, hp: 3000, attack: 100 },
  },
  {
    id: 'art-star-destruction',
    name: '星辰破灭诀',
    type: 'body',
    description: '引星辰之力，破灭万物。攻击力达到极致。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 25000,
    effects: { attack: 1000, defense: 200 },
  },
  {
    id: 'art-universe-devour',
    name: '吞天噬地',
    type: 'mental',
    description: '吞噬天地灵气，修炼速度达到极致。',
    realmRequirement: RealmType.VoidRefining,
    cost: 50000,
    effects: { expRate: 1.0, attack: 500, defense: 500, hp: 10000 },
  },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'spirit-stone-shard',
    name: '灵石碎片',
    type: ItemType.Material,
    description: '含有少量灵气的碎裂灵石。',
    quantity: 5,
    rarity: '普通',
  },
  {
    id: 'refining-stone',
    name: '炼器石',
    type: ItemType.Material,
    description: '用于强化法宝的基础材料。',
    quantity: 10,
    rarity: '普通',
  },
  {
    id: 'healing-herb',
    name: '止血草',
    type: ItemType.Herb,
    description: '常见的草药，用于治疗轻微外伤。',
    quantity: 2,
    rarity: '普通',
    effect: { hp: 20 },
  },
  {
    id: 'spirit-gathering-grass',
    name: '聚灵草',
    type: ItemType.Herb,
    description: '吸收天地灵气的草药，炼制聚气丹的主材。',
    quantity: 5,
    rarity: '普通',
  },
  {
    id: 'iron-sword',
    name: '凡铁剑',
    type: ItemType.Weapon,
    description: '普通的铁剑，聊胜于无。',
    quantity: 1,
    rarity: '普通',
    level: 0,
    isEquippable: true,
    equipmentSlot: EquipmentSlot.Weapon,
    effect: { attack: 5 },
  },
  {
    id: 'cloth-robe',
    name: '粗布道袍',
    type: ItemType.Armor,
    description: '云灵宗外门弟子制式道袍。',
    quantity: 1,
    rarity: '普通',
    level: 0,
    isEquippable: true,
    equipmentSlot: EquipmentSlot.Chest,
    effect: { defense: 3, hp: 10 },
  },
];

export const PILL_RECIPES: Recipe[] = [
  {
    name: '聚气丹',
    cost: 10,
    ingredients: [{ name: '聚灵草', qty: 3 }],
    result: {
      name: '聚气丹',
      type: ItemType.Pill,
      description: '短时间内大幅提升修炼速度（瞬间获得修为）。',
      rarity: '普通',
      effect: { exp: 50 },
    },
  },
  {
    name: '回春丹',
    cost: 20,
    ingredients: [
      { name: '止血草', qty: 3 },
      { name: '聚灵草', qty: 1 },
    ],
    result: {
      name: '回春丹',
      type: ItemType.Pill,
      description: '疗伤圣药，大幅恢复气血。',
      rarity: '稀有',
      effect: { hp: 200 },
    },
  },
  {
    name: '洗髓丹',
    cost: 100,
    ingredients: [
      { name: '紫猴花', qty: 2 },
      { name: '天灵果', qty: 1 },
    ],
    result: {
      name: '洗髓丹',
      type: ItemType.Pill,
      description: '易筋洗髓，脱胎换骨。永久增加少量最大生命值。',
      rarity: '稀有',
      effect: { hp: 50 }, // Treated as permanent in App logic special case or simple maxHp boost
    },
  },
  {
    name: '筑基丹',
    cost: 500,
    ingredients: [
      { name: '千年人参', qty: 2 },
      { name: '妖兽内丹', qty: 1 },
    ],
    result: {
      name: '筑基丹',
      type: ItemType.Pill,
      description: '增加突破到筑基期的几率。服用后获得海量修为。',
      rarity: '传说',
      effect: { exp: 500 },
    },
  },
  {
    name: '龙血丹',
    cost: 2000,
    ingredients: [
      { name: '龙鳞果', qty: 3 },
      { name: '高阶妖丹', qty: 2 },
    ],
    result: {
      name: '龙血丹',
      type: ItemType.Pill,
      description: '蕴含一丝真龙之血，服用后气血如龙。大幅增加气血上限。',
      rarity: '传说',
      effect: { hp: 500 },
    },
  },
  {
    name: '九转金丹',
    cost: 5000,
    ingredients: [
      { name: '万年灵乳', qty: 1 },
      { name: '九叶芝草', qty: 1 },
    ],
    result: {
      name: '九转金丹',
      type: ItemType.Pill,
      description: '传说中的仙丹，服用后甚至能让凡人立地飞升。',
      rarity: '仙品',
      effect: { exp: 5000, attack: 10, defense: 10 },
    },
  },
];

// 可通过历练获得的额外丹方（这些不会在初始炼丹面板中显示，需要通过使用丹方物品解锁）
export const DISCOVERABLE_RECIPES: Recipe[] = [
  {
    name: '凝神丹',
    cost: 150,
    ingredients: [
      { name: '凝神花', qty: 3 },
      { name: '聚灵草', qty: 2 },
    ],
    result: {
      name: '凝神丹',
      type: ItemType.Pill,
      description: '凝神静气，提升神识。永久增加神识属性。',
      rarity: '稀有',
      effect: { spirit: 20 },
    },
  },
  {
    name: '强体丹',
    cost: 200,
    ingredients: [
      { name: '血参', qty: 2 },
      { name: '回气草', qty: 3 },
    ],
    result: {
      name: '强体丹',
      type: ItemType.Pill,
      description: '强身健体，提升体魄。永久增加体魄属性。',
      rarity: '稀有',
      effect: { physique: 20 },
    },
  },
  {
    name: '破境丹',
    cost: 800,
    ingredients: [
      { name: '千年灵芝', qty: 1 },
      { name: '妖兽内丹', qty: 2 },
    ],
    result: {
      name: '破境丹',
      type: ItemType.Pill,
      description: '突破境界的辅助丹药，大幅提升修为。',
      rarity: '传说',
      effect: { exp: 1000 },
    },
  },
  {
    name: '仙灵丹',
    cost: 3000,
    ingredients: [
      { name: '万年仙草', qty: 1 },
      { name: '高阶妖丹', qty: 3 },
    ],
    result: {
      name: '仙灵丹',
      type: ItemType.Pill,
      description: '仙家灵丹，服用后修为与属性大幅提升。',
      rarity: '传说',
      effect: { exp: 2000, spirit: 50, physique: 50 },
    },
  },
  {
    name: '天元丹',
    cost: 10000,
    ingredients: [
      { name: '万年灵乳', qty: 2 },
      { name: '九叶芝草', qty: 2 },
      { name: '龙鳞果', qty: 5 },
    ],
    result: {
      name: '天元丹',
      type: ItemType.Pill,
      description: '天元级别的仙丹，服用后全属性大幅提升。',
      rarity: '仙品',
      effect: {
        exp: 10000,
        attack: 50,
        defense: 50,
        spirit: 100,
        physique: 100,
        speed: 30,
      },
    },
  },
];

// Upgrade Constants
export const UPGRADE_MATERIAL_NAME = '炼器石';
export const UPGRADE_STONE_NAME = '强化石';
export const BASE_UPGRADE_COST_STONES = 50;
export const BASE_UPGRADE_COST_MATS = 2;
export const UPGRADE_STONE_SUCCESS_BONUS = 0.1; // 每颗强化石提高10%成功率

// Returns percentage increase (0.1 = 10%)
export const getUpgradeMultiplier = (rarity: ItemRarity = '普通') => {
  switch (rarity) {
    case '普通':
      return 0.1;
    case '稀有':
      return 0.15;
    case '传说':
      return 0.2;
    case '仙品':
      return 0.25;
    default:
      return 0.1;
  }
};

// --- SECT CONSTANTS ---

export type SectGrade = '天' | '地' | '玄' | '黄'; // 宗门等级：天最高，黄最低

export interface SectInfo {
  id: string;
  name: string;
  description: string;
  reqRealm: RealmType;
  grade: SectGrade; // 宗门等级
  exitCost?: {
    // 安全退出宗门的代价
    spiritStones?: number;
    items?: { name: string; quantity: number }[];
  };
}

export const SECTS: SectInfo[] = [
  {
    id: 'sect-cloud',
    name: '云灵宗',
    description: '正道大宗，门风清正，适合大部分修士。',
    reqRealm: RealmType.QiRefining,
    grade: '玄',
    exitCost: {
      spiritStones: 500,
      items: [{ name: '聚灵草', quantity: 10 }],
    },
  },
  {
    id: 'sect-fire',
    name: '烈阳宗',
    description: '坐落于火山之上，专修火法，行事霸道。',
    reqRealm: RealmType.Foundation,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '炼器石', quantity: 20 }],
    },
  },
  {
    id: 'sect-sword',
    name: '万剑门',
    description: '一剑破万法。门徒皆为剑痴，攻击力极强。',
    reqRealm: RealmType.Foundation,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '精铁', quantity: 15 }],
    },
  },
  {
    id: 'sect-temple',
    name: '天音寺',
    description: '佛门圣地，慈悲为怀，防御力出众。',
    reqRealm: RealmType.QiRefining,
    grade: '玄',
    exitCost: {
      spiritStones: 500,
      items: [{ name: '止血草', quantity: 10 }],
    },
  },
  {
    id: 'sect-taoist',
    name: '太虚观',
    description: '道门正统，修炼速度极快。',
    reqRealm: RealmType.Foundation,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '聚灵草', quantity: 15 }],
    },
  },
  {
    id: 'sect-blood',
    name: '血魔宗',
    description: '魔道宗门，行事狠辣，但实力强大。',
    reqRealm: RealmType.GoldenCore,
    grade: '天',
    exitCost: {
      spiritStones: 10000,
      items: [{ name: '妖兽内丹', quantity: 5 }],
    },
  },
  {
    id: 'sect-lotus',
    name: '青莲剑派',
    description: '剑修圣地，剑法精妙。',
    reqRealm: RealmType.Foundation,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '精铁', quantity: 15 }],
    },
  },
  {
    id: 'sect-xuantian',
    name: '玄天宗',
    description: '正道大宗，底蕴深厚。',
    reqRealm: RealmType.GoldenCore,
    grade: '天',
    exitCost: {
      spiritStones: 10000,
      items: [{ name: '千年人参', quantity: 3 }],
    },
  },
  {
    id: 'sect-jiuyou',
    name: '九幽门',
    description: '魔道宗门，阴险狡诈。',
    reqRealm: RealmType.GoldenCore,
    grade: '天',
    exitCost: {
      spiritStones: 10000,
      items: [{ name: '妖兽内丹', quantity: 5 }],
    },
  },
  {
    id: 'sect-star',
    name: '星辰阁',
    description: '神秘组织，掌握星辰之力。',
    reqRealm: RealmType.NascentSoul,
    grade: '天',
    exitCost: {
      spiritStones: 50000,
      items: [{ name: '星辰石', quantity: 10 }],
    },
  },
  {
    id: 'sect-dragon',
    name: '龙族圣地',
    description: '龙族后裔建立的宗门，血脉强大。',
    reqRealm: RealmType.NascentSoul,
    grade: '天',
    exitCost: {
      spiritStones: 50000,
      items: [{ name: '龙鳞果', quantity: 5 }],
    },
  },
  {
    id: 'sect-phoenix',
    name: '凤凰宫',
    description: '凤凰血脉传承，涅槃重生。',
    reqRealm: RealmType.NascentSoul,
    grade: '天',
    exitCost: {
      spiritStones: 50000,
      items: [{ name: '九叶芝草', quantity: 3 }],
    },
  },
  {
    id: 'sect-thunder',
    name: '雷神殿',
    description: '专修雷法，攻击力极强。',
    reqRealm: RealmType.GoldenCore,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '炼器石', quantity: 20 }],
    },
  },
  {
    id: 'sect-ice',
    name: '冰魄宗',
    description: '冰属性修士的圣地，防御力强。',
    reqRealm: RealmType.Foundation,
    grade: '黄',
    exitCost: {
      spiritStones: 300,
      items: [{ name: '聚灵草', quantity: 5 }],
    },
  },
  {
    id: 'sect-poison',
    name: '毒王谷',
    description: '毒修聚集地，擅长用毒。',
    reqRealm: RealmType.Foundation,
    grade: '黄',
    exitCost: {
      spiritStones: 300,
      items: [{ name: '止血草', quantity: 5 }],
    },
  },
  {
    id: 'sect-illusion',
    name: '幻月门',
    description: '幻术宗门，擅长迷惑敌人。',
    reqRealm: RealmType.Foundation,
    grade: '黄',
    exitCost: {
      spiritStones: 300,
      items: [{ name: '聚灵草', quantity: 5 }],
    },
  },
  {
    id: 'sect-diamond',
    name: '金刚寺',
    description: '体修宗门，肉身强大。',
    reqRealm: RealmType.QiRefining,
    grade: '玄',
    exitCost: {
      spiritStones: 500,
      items: [{ name: '炼器石', quantity: 10 }],
    },
  },
  {
    id: 'sect-yinyang',
    name: '阴阳教',
    description: '阴阳调和，攻防兼备。',
    reqRealm: RealmType.GoldenCore,
    grade: '地',
    exitCost: {
      spiritStones: 2000,
      items: [{ name: '聚灵草', quantity: 15 }],
    },
  },
];

export const SECT_RANK_REQUIREMENTS: Record<
  SectRank,
  { contribution: number; realmIndex: number }
> = {
  [SectRank.Outer]: { contribution: 0, realmIndex: 0 },
  [SectRank.Inner]: { contribution: 500, realmIndex: 1 }, // Foundation
  [SectRank.Core]: { contribution: 2000, realmIndex: 2 }, // Golden Core
  [SectRank.Elder]: { contribution: 10000, realmIndex: 3 }, // Nascent Soul
};

export const SECT_SHOP_ITEMS: {
  name: string;
  cost: number;
  item: Omit<Item, 'id'>;
}[] = [
  {
    name: '炼器石',
    cost: 10,
    item: {
      name: '炼器石',
      type: ItemType.Material,
      description: '用于强化法宝的基础材料。',
      quantity: 1,
      rarity: '普通',
    },
  },
  {
    name: '聚气丹',
    cost: 20,
    item: {
      name: '聚气丹',
      type: ItemType.Pill,
      description: '短时间内大幅提升修炼速度。',
      quantity: 1,
      rarity: '普通',
      effect: { exp: 50 },
    },
  },
  {
    name: '紫猴花',
    cost: 50,
    item: {
      name: '紫猴花',
      type: ItemType.Herb,
      description: '炼制洗髓丹的材料，生长在悬崖峭壁。',
      quantity: 1,
      rarity: '稀有',
    },
  },
  {
    name: '洗髓丹',
    cost: 100,
    item: {
      name: '洗髓丹',
      type: ItemType.Pill,
      description: '强身健体，略微提升最大气血。',
      quantity: 1,
      rarity: '稀有',
      effect: { hp: 50 },
    },
  },
  {
    name: '筑基丹',
    cost: 1000,
    item: {
      name: '筑基丹',
      type: ItemType.Pill,
      description: '增加突破到筑基期的几率。',
      quantity: 1,
      rarity: '传说',
      effect: { exp: 500 },
    },
  },
  {
    name: '高阶妖丹',
    cost: 500,
    item: {
      name: '高阶妖丹',
      type: ItemType.Material,
      description: '强大妖兽的内丹，灵气逼人。',
      quantity: 1,
      rarity: '稀有',
    },
  },
];

// --- SECRET REALMS ---

export const SECRET_REALMS: SecretRealm[] = [
  {
    id: 'realm-beast-mountain',
    name: '万兽山脉',
    description:
      '外围相对安全，深处盘踞着可怕的妖兽。适合炼气、筑基期修士历练。',
    minRealm: RealmType.QiRefining,
    cost: 80,
    riskLevel: '中',
    drops: ['妖兽材料', '稀有草药', '攻击法器'],
  },
  {
    id: 'realm-ancient-tomb',
    name: '上古剑冢',
    description: '传说中上古剑修的埋骨之地，剑气纵横。非筑基期不可入。',
    minRealm: RealmType.Foundation,
    cost: 300,
    riskLevel: '高',
    drops: ['剑修功法', '残破灵宝', '剑意草'],
  },
  {
    id: 'realm-thunder-purgatory',
    name: '雷罚炼狱',
    description: '终年雷霆不息，稍有不慎便会灰飞烟灭。',
    minRealm: RealmType.GoldenCore,
    cost: 800,
    riskLevel: '极度危险',
    drops: ['雷属性至宝', '仙品丹药材料', '天阶功法'],
  },
];

// --- 角色系统：天赋 ---
export const TALENTS: Talent[] = [
  // 普通天赋（3个）
  {
    id: 'talent-ordinary',
    name: '凡体',
    description: '普通的修仙资质，没有任何特殊加成。',
    rarity: '普通',
    effects: {},
  },
  {
    id: 'talent-strong-body',
    name: '强健体魄',
    description: '身体比常人强壮一些，气血略微提升。',
    rarity: '普通',
    effects: { hp: 50 },
  },
  {
    id: 'talent-quick-learner',
    name: '悟性尚可',
    description: '学习能力稍强，修炼速度略微提升。',
    rarity: '普通',
    effects: { expRate: 0.05 },
  },

  // 稀有天赋（8个）
  {
    id: 'talent-spirit-root',
    name: '灵根',
    description: '拥有灵根，修炼速度提升10%。',
    rarity: '稀有',
    effects: { expRate: 0.1 },
  },
  {
    id: 'talent-iron-bone',
    name: '铁骨',
    description: '骨骼坚硬，防御力提升。',
    rarity: '稀有',
    effects: { defense: 30, physique: 20 },
  },
  {
    id: 'talent-sharp-blade',
    name: '利刃',
    description: '天生适合使用武器，攻击力提升。',
    rarity: '稀有',
    effects: { attack: 40 },
  },
  {
    id: 'talent-spirit-sense',
    name: '神识敏锐',
    description: '神识天生敏锐，神识和速度提升。',
    rarity: '稀有',
    effects: { spirit: 25, speed: 15 },
  },
  {
    id: 'talent-vitality',
    name: '生机勃勃',
    description: '生命力旺盛，气血上限大幅提升。',
    rarity: '稀有',
    effects: { hp: 150, physique: 15 },
  },
  {
    id: 'talent-fast-cultivation',
    name: '修炼奇才',
    description: '修炼天赋出众，修炼速度提升15%。',
    rarity: '稀有',
    effects: { expRate: 0.15 },
  },
  {
    id: 'talent-lucky',
    name: '小有气运',
    description: '运气不错，幸运值提升。',
    rarity: '稀有',
    effects: { luck: 20 },
  },
  {
    id: 'talent-balanced',
    name: '均衡发展',
    description: '各项属性均衡提升。',
    rarity: '稀有',
    effects: {
      attack: 20,
      defense: 20,
      hp: 80,
      spirit: 15,
      physique: 15,
      speed: 10,
    },
  },

  // 传说天赋（6个）
  {
    id: 'talent-immortal-body',
    name: '仙体',
    description: '天生仙体，气血和防御大幅提升。',
    rarity: '传说',
    effects: { hp: 200, defense: 50 },
  },
  {
    id: 'talent-sword-heart',
    name: '剑心',
    description: '天生剑心，攻击力大幅提升。',
    rarity: '传说',
    effects: { attack: 100 },
  },
  {
    id: 'talent-thunder-body',
    name: '雷体',
    description: '拥有雷属性体质，攻击和速度大幅提升。',
    rarity: '传说',
    effects: { attack: 80, speed: 40, spirit: 30 },
  },
  {
    id: 'talent-dragon-blood',
    name: '龙血',
    description: '体内流淌着龙族血脉，气血和体魄大幅提升。',
    rarity: '传说',
    effects: { hp: 300, physique: 50, defense: 40 },
  },
  {
    id: 'talent-genius',
    name: '修炼天才',
    description: '修炼天赋绝佳，修炼速度大幅提升。',
    rarity: '传说',
    effects: { expRate: 0.25, spirit: 40 },
  },
  {
    id: 'talent-blessed',
    name: '天眷之人',
    description: '受天道眷顾，幸运值和修炼速度提升。',
    rarity: '传说',
    effects: { luck: 35, expRate: 0.15 },
  },

  // 仙品天赋（3个）
  {
    id: 'talent-lucky-star',
    name: '天运之子',
    description: '受天道眷顾，幸运值大幅提升，更容易遇到奇遇。',
    rarity: '仙品',
    effects: { luck: 50, expRate: 0.2 },
  },
  {
    id: 'talent-immortal-king',
    name: '仙王转世',
    description: '疑似仙王转世，各项属性大幅提升，修炼速度极快。',
    rarity: '仙品',
    effects: {
      attack: 150,
      defense: 100,
      hp: 400,
      spirit: 60,
      physique: 60,
      speed: 50,
      expRate: 0.3,
    },
  },
  {
    id: 'talent-chaos-body',
    name: '混沌之体',
    description: '拥有传说中的混沌之体，所有属性全面提升，修炼速度极快。',
    rarity: '仙品',
    effects: {
      attack: 120,
      defense: 80,
      hp: 350,
      spirit: 50,
      physique: 50,
      speed: 40,
      expRate: 0.25,
      luck: 30,
    },
  },
];

// --- 角色系统：称号 ---
export const TITLES: Title[] = [
  {
    id: 'title-novice',
    name: '初入仙途',
    description: '刚刚踏入修仙之路的新人。',
    requirement: '初始称号',
    effects: {},
  },
  {
    id: 'title-foundation',
    name: '筑基修士',
    description: '成功筑基，正式踏入修仙门槛。',
    requirement: '达到筑基期',
    effects: { attack: 10, defense: 5 },
  },
  {
    id: 'title-golden-core',
    name: '金丹真人',
    description: '凝聚金丹，已是修仙界的中流砥柱。',
    requirement: '达到金丹期',
    effects: { attack: 50, defense: 25, hp: 200 },
  },
  {
    id: 'title-nascent-soul',
    name: '元婴老祖',
    description: '修成元婴，可称一方老祖。',
    requirement: '达到元婴期',
    effects: { attack: 200, defense: 100, hp: 1000 },
  },
  {
    id: 'title-immortal',
    name: '飞升仙人',
    description: '渡劫飞升，已是真正的仙人。',
    requirement: '达到渡劫飞升',
    effects: { attack: 1000, defense: 500, hp: 5000, expRate: 0.3 },
  },
];

// --- 奇遇系统 ---
export const ENCOUNTER_EVENTS: EncounterEvent[] = [
  {
    id: 'encounter-herb',
    name: '发现灵草',
    description: '你在山间发现了一株珍贵的灵草。',
    rarity: '普通',
    triggerChance: 0.3,
    rewards: {
      exp: 20,
      items: [{ name: '聚灵草', rarity: '普通', quantity: 1 }],
    },
  },
  {
    id: 'encounter-spirit-stone',
    name: '灵石矿脉',
    description: '你意外发现了一处小型灵石矿脉。',
    rarity: '稀有',
    triggerChance: 0.15,
    rewards: {
      spiritStones: 100,
      exp: 50,
    },
  },
  {
    id: 'encounter-ancient-cave',
    name: '古修士洞府',
    description: '你发现了一处古修士遗留的洞府，获得了珍贵的传承。',
    rarity: '传说',
    triggerChance: 0.05,
    minRealm: RealmType.Foundation,
    requirements: { minLuck: 30 },
    rewards: {
      exp: 500,
      spiritStones: 500,
      items: [{ name: '上古功法残卷', rarity: '传说', quantity: 1 }],
    },
  },
  {
    id: 'encounter-immortal-herb',
    name: '万年仙草',
    description: '你遇到了传说中的万年仙草，这是天大的机缘！',
    rarity: '仙品',
    triggerChance: 0.01,
    minRealm: RealmType.GoldenCore,
    requirements: { minLuck: 50 },
    rewards: {
      exp: 2000,
      items: [{ name: '万年仙草', rarity: '仙品', quantity: 1 }],
    },
  },
];

// --- 探索系统 ---
export const EXPLORATION_LOCATIONS: ExplorationLocation[] = [
  {
    id: 'explore-forest',
    name: '迷雾森林',
    description: '常年被迷雾笼罩的森林，隐藏着许多秘密。',
    minRealm: RealmType.QiRefining,
    cost: 20,
    riskLevel: '低',
    eventTypes: ['normal', 'lucky'],
  },
  {
    id: 'explore-mountain',
    name: '天柱山',
    description: '高耸入云的山峰，传说有仙人居住。',
    minRealm: RealmType.Foundation,
    cost: 50,
    riskLevel: '中',
    eventTypes: ['normal', 'lucky'],
    specialEncounters: ['encounter-ancient-cave'],
  },
  {
    id: 'explore-abyss',
    name: '无底深渊',
    description: '深不见底的深渊，危险与机遇并存。',
    minRealm: RealmType.GoldenCore,
    cost: 200,
    riskLevel: '高',
    eventTypes: ['normal', 'lucky', 'secret_realm'],
    specialEncounters: ['encounter-immortal-herb'],
  },
];

// --- 成就系统 ---
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-step',
    name: '第一步',
    description: '完成第一次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'custom', value: 1, target: 'meditate' },
    reward: { exp: 50, spiritStones: 10 },
    rarity: '普通',
  },
  {
    id: 'ach-foundation',
    name: '筑基成功',
    description: '突破到筑基期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.Foundation },
    reward: { exp: 500, spiritStones: 200, titleId: 'title-foundation' },
    rarity: '稀有',
  },
  {
    id: 'ach-golden-core',
    name: '金丹大道',
    description: '突破到金丹期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.GoldenCore },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-golden-core' },
    rarity: '传说',
  },
  {
    id: 'ach-first-kill',
    name: '初战告捷',
    description: '在历练中击败第一个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 1 },
    reward: { exp: 100, spiritStones: 50 },
    rarity: '普通',
  },
  {
    id: 'ach-collector',
    name: '收藏家',
    description: '收集10种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 10 },
    reward: { exp: 300, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-immortal',
    name: '飞升成仙',
    description: '达到渡劫飞升境界',
    category: 'special',
    requirement: {
      type: 'realm',
      value: 1,
      target: RealmType.ImmortalAscension,
    },
    reward: { exp: 10000, spiritStones: 10000, titleId: 'title-immortal' },
    rarity: '仙品',
  },
  // 新增20个成就
  {
    id: 'ach-nascent-soul',
    name: '元婴出窍',
    description: '突破到元婴期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.NascentSoul },
    reward: { exp: 5000, spiritStones: 3000 },
    rarity: '传说',
  },
  {
    id: 'ach-spirit-severing',
    name: '化神之境',
    description: '突破到化神期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.SpiritSevering },
    reward: { exp: 8000, spiritStones: 5000 },
    rarity: '传说',
  },
  {
    id: 'ach-void-refining',
    name: '炼虚合道',
    description: '突破到炼虚期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.VoidRefining },
    reward: { exp: 12000, spiritStones: 8000 },
    rarity: '仙品',
  },
  {
    id: 'ach-killer-10',
    name: '十人斩',
    description: '击败10个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 10 },
    reward: { exp: 200, spiritStones: 100 },
    rarity: '普通',
  },
  {
    id: 'ach-killer-50',
    name: '百战不殆',
    description: '击败50个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 50 },
    reward: { exp: 1000, spiritStones: 500 },
    rarity: '稀有',
  },
  {
    id: 'ach-killer-100',
    name: '千人斩',
    description: '击败100个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 100 },
    reward: { exp: 3000, spiritStones: 1500 },
    rarity: '传说',
  },
  {
    id: 'ach-collector-20',
    name: '物品收藏家',
    description: '收集20种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 20 },
    reward: { exp: 500, spiritStones: 300 },
    rarity: '稀有',
  },
  {
    id: 'ach-collector-50',
    name: '收藏大师',
    description: '收集50种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 50 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: '传说',
  },
  {
    id: 'ach-meditate-10',
    name: '勤修不辍',
    description: '完成10次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 10 },
    reward: { exp: 150, spiritStones: 50 },
    rarity: '普通',
  },
  {
    id: 'ach-meditate-50',
    name: '闭关苦修',
    description: '完成50次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 50 },
    reward: { exp: 800, spiritStones: 300 },
    rarity: '稀有',
  },
  {
    id: 'ach-meditate-100',
    name: '道心坚定',
    description: '完成100次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 100 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: '传说',
  },
  {
    id: 'ach-adventure-20',
    name: '历练新手',
    description: '完成20次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 20 },
    reward: { exp: 300, spiritStones: 150 },
    rarity: '普通',
  },
  {
    id: 'ach-adventure-100',
    name: '历练老手',
    description: '完成100次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 100 },
    reward: { exp: 1500, spiritStones: 800 },
    rarity: '稀有',
  },
  {
    id: 'ach-equip-5',
    name: '装备齐全',
    description: '装备5件物品',
    category: 'collection',
    requirement: { type: 'equip', value: 5 },
    reward: { exp: 200, spiritStones: 100 },
    rarity: '普通',
  },
  {
    id: 'ach-pet-1',
    name: '灵宠伙伴',
    description: '获得第一个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 1 },
    reward: { exp: 500, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-pet-3',
    name: '灵宠大师',
    description: '获得3个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 3 },
    reward: { exp: 1500, spiritStones: 800 },
    rarity: '传说',
  },
  {
    id: 'ach-recipe-5',
    name: '丹道入门',
    description: '解锁5个丹方',
    category: 'collection',
    requirement: { type: 'recipe', value: 5 },
    reward: { exp: 400, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-3',
    name: '功法初成',
    description: '学习3种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 3 },
    reward: { exp: 600, spiritStones: 300 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-10',
    name: '功法大成',
    description: '学习10种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 10 },
    reward: { exp: 3000, spiritStones: 1500 },
    rarity: '传说',
  },
  {
    id: 'ach-breakthrough-5',
    name: '突破达人',
    description: '完成5次突破',
    category: 'cultivation',
    requirement: { type: 'breakthrough', value: 5 },
    reward: { exp: 1000, spiritStones: 500 },
    rarity: '稀有',
  },
  {
    id: 'ach-secret-realm-5',
    name: '秘境探索者',
    description: '进入5次秘境',
    category: 'exploration',
    requirement: { type: 'secret_realm', value: 5 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: '传说',
  },
  {
    id: 'ach-lottery-10',
    name: '抽奖新手',
    description: '进行10次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 10 },
    reward: { exp: 300, spiritStones: 200 },
    rarity: '普通',
  },
  {
    id: 'ach-lottery-50',
    name: '抽奖达人',
    description: '进行50次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 50 },
    reward: { exp: 2000, spiritStones: 1500 },
    rarity: '稀有',
  },
];

// --- 灵宠系统 ---
export const PET_SKILLS: PetSkill[] = [
  {
    id: 'skill-bite',
    name: '撕咬',
    description: '基础攻击技能',
    type: 'attack',
    effect: { damage: 10 },
  },
  {
    id: 'skill-heal',
    name: '治愈之光',
    description: '为主人恢复气血',
    type: 'support',
    effect: { heal: 50 },
  },
  {
    id: 'skill-protect',
    name: '守护',
    description: '提升主人防御',
    type: 'defense',
    effect: { buff: { defense: 20 } },
  },
  {
    id: 'skill-blessing',
    name: '祝福',
    description: '提升主人攻击和防御',
    type: 'support',
    effect: { buff: { attack: 30, defense: 15 } },
  },
];

export const PET_TEMPLATES: PetTemplate[] = [
  {
    id: 'pet-spirit-fox',
    name: '灵狐',
    species: '狐族',
    description: '聪明伶俐的灵狐，擅长辅助。',
    rarity: '普通',
    baseStats: { attack: 20, defense: 15, hp: 100, speed: 30 },
    skills: [
      {
        id: 'skill-bite',
        name: '撕咬',
        description: '基础攻击',
        type: 'attack',
        effect: { damage: 10 },
      },
      {
        id: 'skill-heal',
        name: '治愈之光',
        description: '恢复气血',
        type: 'support',
        effect: { heal: 50 },
      },
    ],
    evolutionRequirements: {
      level: 10,
      items: [{ name: '聚灵草', quantity: 10 }],
    },
  },
  {
    id: 'pet-thunder-tiger',
    name: '雷虎',
    species: '虎族',
    description: '凶猛威武的雷虎，攻击力极强。',
    rarity: '稀有',
    baseStats: { attack: 50, defense: 30, hp: 200, speed: 40 },
    skills: [
      {
        id: 'skill-bite',
        name: '撕咬',
        description: '基础攻击',
        type: 'attack',
        effect: { damage: 30 },
      },
      {
        id: 'skill-thunder',
        name: '雷击',
        description: '雷属性攻击',
        type: 'attack',
        effect: { damage: 50 },
      },
    ],
    evolutionRequirements: {
      level: 20,
      items: [{ name: '妖兽内丹', quantity: 5 }],
    },
  },
  {
    id: 'pet-phoenix',
    name: '凤凰',
    species: '神兽',
    description: '传说中的神兽凤凰，拥有强大的力量。',
    rarity: '仙品',
    baseStats: { attack: 200, defense: 150, hp: 1000, speed: 80 },
    skills: [
      {
        id: 'skill-blessing',
        name: '祝福',
        description: '提升属性',
        type: 'support',
        effect: { buff: { attack: 50, defense: 30 } },
      },
      {
        id: 'skill-rebirth',
        name: '涅槃',
        description: '复活主人',
        type: 'support',
        effect: { heal: 9999 },
      },
    ],
  },
];

// --- 抽奖系统 ---
export const LOTTERY_PRIZES: LotteryPrize[] = [
  // 普通奖励 - 灵石
  {
    id: 'lottery-stone-10',
    name: '10灵石',
    type: 'spiritStones',
    rarity: '普通',
    weight: 35,
    value: { spiritStones: 10 },
  },
  {
    id: 'lottery-stone-50',
    name: '50灵石',
    type: 'spiritStones',
    rarity: '普通',
    weight: 25,
    value: { spiritStones: 50 },
  },
  {
    id: 'lottery-stone-100',
    name: '100灵石',
    type: 'spiritStones',
    rarity: '稀有',
    weight: 18,
    value: { spiritStones: 100 },
  },
  {
    id: 'lottery-stone-500',
    name: '500灵石',
    type: 'spiritStones',
    rarity: '稀有',
    weight: 8,
    value: { spiritStones: 500 },
  },
  {
    id: 'lottery-stone-1000',
    name: '1000灵石',
    type: 'spiritStones',
    rarity: '传说',
    weight: 3,
    value: { spiritStones: 1000 },
  },

  // 普通奖励 - 修为
  {
    id: 'lottery-exp-50',
    name: '50修为',
    type: 'exp',
    rarity: '普通',
    weight: 30,
    value: { exp: 50 },
  },
  {
    id: 'lottery-exp-200',
    name: '200修为',
    type: 'exp',
    rarity: '普通',
    weight: 20,
    value: { exp: 200 },
  },
  {
    id: 'lottery-exp-500',
    name: '500修为',
    type: 'exp',
    rarity: '稀有',
    weight: 12,
    value: { exp: 500 },
  },
  {
    id: 'lottery-exp-2000',
    name: '2000修为',
    type: 'exp',
    rarity: '传说',
    weight: 4,
    value: { exp: 2000 },
  },

  // 普通奖励 - 丹药
  {
    id: 'lottery-pill-qi',
    name: '聚气丹',
    type: 'item',
    rarity: '普通',
    weight: 18,
    value: {
      item: {
        name: '聚气丹',
        type: ItemType.Pill,
        description: '短时间内大幅提升修炼速度',
        quantity: 1,
        rarity: '普通',
        effect: { exp: 50 },
      },
    },
  },
  {
    id: 'lottery-pill-qi-2',
    name: '聚气丹x3',
    type: 'item',
    rarity: '普通',
    weight: 12,
    value: {
      item: {
        name: '聚气丹',
        type: ItemType.Pill,
        description: '短时间内大幅提升修炼速度',
        quantity: 3,
        rarity: '普通',
        effect: { exp: 50 },
      },
    },
  },
  {
    id: 'lottery-pill-heal',
    name: '回春丹',
    type: 'item',
    rarity: '普通',
    weight: 15,
    value: {
      item: {
        name: '回春丹',
        type: ItemType.Pill,
        description: '疗伤圣药，大幅恢复气血',
        quantity: 1,
        rarity: '稀有',
        effect: { hp: 200 },
      },
    },
  },
  {
    id: 'lottery-pill-marrow',
    name: '洗髓丹',
    type: 'item',
    rarity: '稀有',
    weight: 10,
    value: {
      item: {
        name: '洗髓丹',
        type: ItemType.Pill,
        description: '易筋洗髓，脱胎换骨',
        quantity: 1,
        rarity: '稀有',
        effect: { hp: 50 },
      },
    },
  },
  {
    id: 'lottery-pill-foundation',
    name: '筑基丹',
    type: 'item',
    rarity: '稀有',
    weight: 8,
    value: {
      item: {
        name: '筑基丹',
        type: ItemType.Pill,
        description: '增加突破到筑基期的几率',
        quantity: 1,
        rarity: '传说',
        effect: { exp: 500 },
      },
    },
  },
  {
    id: 'lottery-pill-golden',
    name: '结金丹',
    type: 'item',
    rarity: '传说',
    weight: 6,
    value: {
      item: {
        name: '结金丹',
        type: ItemType.Pill,
        description: '有助于凝结金丹的珍贵丹药',
        quantity: 1,
        rarity: '稀有',
        effect: { exp: 30000, spirit: 20 },
      },
    },
  },
  {
    id: 'lottery-pill-soul',
    name: '凝魂丹',
    type: 'item',
    rarity: '传说',
    weight: 4,
    value: {
      item: {
        name: '凝魂丹',
        type: ItemType.Pill,
        description: '能够凝聚神魂的珍贵丹药',
        quantity: 1,
        rarity: '传说',
        effect: { exp: 10000, spirit: 50, hp: 300 },
      },
    },
  },
  {
    id: 'lottery-pill-dragon',
    name: '龙血丹',
    type: 'item',
    rarity: '传说',
    weight: 3,
    value: {
      item: {
        name: '龙血丹',
        type: ItemType.Pill,
        description: '蕴含一丝真龙之血，气血如龙',
        quantity: 1,
        rarity: '传说',
        effect: { hp: 500, attack: 20, defense: 20 },
      },
    },
  },
  {
    id: 'lottery-pill-phoenix',
    name: '凤凰涅槃丹',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '凤凰涅槃丹',
        type: ItemType.Pill,
        description: '蕴含凤凰涅槃之力的神丹',
        quantity: 1,
        rarity: '传说',
        effect: { hp: 800, exp: 1500, attack: 30 },
      },
    },
  },
  {
    id: 'lottery-pill-immortal',
    name: '九转金丹',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '九转金丹',
        type: ItemType.Pill,
        description: '传说中的仙丹，能让凡人立地飞升',
        quantity: 1,
        rarity: '仙品',
        effect: { exp: 5000, attack: 10, defense: 10 },
      },
    },
  },

  // 普通奖励 - 材料
  {
    id: 'lottery-material-refining',
    name: '炼器石',
    type: 'item',
    rarity: '普通',
    weight: 16,
    value: {
      item: {
        name: '炼器石',
        type: ItemType.Material,
        description: '用于强化法宝的基础材料',
        quantity: 5,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-refining-2',
    name: '炼器石x10',
    type: 'item',
    rarity: '普通',
    weight: 10,
    value: {
      item: {
        name: '炼器石',
        type: ItemType.Material,
        description: '用于强化法宝的基础材料',
        quantity: 10,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-upgrade-stone',
    name: '强化石',
    type: 'item',
    rarity: '稀有',
    weight: 10,
    value: {
      item: {
        name: '强化石',
        type: ItemType.Material,
        description: '提高装备强化成功率的珍贵材料，每颗可提高10%成功率',
        quantity: 1,
        rarity: '稀有',
      },
    },
  },
  {
    id: 'lottery-material-upgrade-stone-3',
    name: '强化石x10',
    type: 'item',
    rarity: '传说',
    weight: 3,
    value: {
      item: {
        name: '强化石',
        type: ItemType.Material,
        description: '提高装备强化成功率的珍贵材料，每颗可提高10%成功率',
        quantity: 10,
        rarity: '稀有',
      },
    },
  },
  {
    id: 'lottery-material-spirit',
    name: '灵石碎片',
    type: 'item',
    rarity: '普通',
    weight: 14,
    value: {
      item: {
        name: '灵石碎片',
        type: ItemType.Material,
        description: '破碎的灵石，可用于炼器',
        quantity: 10,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-iron',
    name: '精铁',
    type: 'item',
    rarity: '普通',
    weight: 12,
    value: {
      item: {
        name: '精铁',
        type: ItemType.Material,
        description: '经过提炼的精铁，是炼器的好材料',
        quantity: 5,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-silver',
    name: '秘银',
    type: 'item',
    rarity: '稀有',
    weight: 7,
    value: {
      item: {
        name: '秘银',
        type: ItemType.Material,
        description: '珍贵的炼器材料，能够提升法宝品质',
        quantity: 3,
        rarity: '稀有',
      },
    },
  },
  {
    id: 'lottery-material-dragon-scale',
    name: '龙鳞',
    type: 'item',
    rarity: '传说',
    weight: 3,
    value: {
      item: {
        name: '龙鳞',
        type: ItemType.Material,
        description: '真龙身上的鳞片，是炼制顶级法宝的材料',
        quantity: 1,
        rarity: '传说',
      },
    },
  },
  {
    id: 'lottery-material-herb',
    name: '聚灵草',
    type: 'item',
    rarity: '普通',
    weight: 15,
    value: {
      item: {
        name: '聚灵草',
        type: ItemType.Herb,
        description: '吸收天地灵气的草药',
        quantity: 10,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-herb-2',
    name: '聚灵草x20',
    type: 'item',
    rarity: '普通',
    weight: 10,
    value: {
      item: {
        name: '聚灵草',
        type: ItemType.Herb,
        description: '吸收天地灵气的草药',
        quantity: 20,
        rarity: '普通',
      },
    },
  },
  {
    id: 'lottery-material-rare',
    name: '紫猴花',
    type: 'item',
    rarity: '稀有',
    weight: 8,
    value: {
      item: {
        name: '紫猴花',
        type: ItemType.Herb,
        description: '炼制洗髓丹的材料',
        quantity: 3,
        rarity: '稀有',
      },
    },
  },
  {
    id: 'lottery-material-snow-lotus',
    name: '雪莲花',
    type: 'item',
    rarity: '稀有',
    weight: 6,
    value: {
      item: {
        name: '雪莲花',
        type: ItemType.Herb,
        description: '生长在极寒之地的灵花，药效极强',
        quantity: 2,
        rarity: '稀有',
      },
    },
  },
  {
    id: 'lottery-material-legend',
    name: '千年人参',
    type: 'item',
    rarity: '传说',
    weight: 4,
    value: {
      item: {
        name: '千年人参',
        type: ItemType.Herb,
        description: '千年灵药，珍贵无比',
        quantity: 2,
        rarity: '传说',
      },
    },
  },
  {
    id: 'lottery-material-phoenix-feather',
    name: '凤凰羽',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '凤凰羽',
        type: ItemType.Material,
        description: '凤凰身上的羽毛，蕴含涅槃之力',
        quantity: 1,
        rarity: '传说',
      },
    },
  },

  // 普通奖励 - 装备（武器）
  {
    id: 'lottery-weapon-iron',
    name: '精铁剑',
    type: 'item',
    rarity: '普通',
    weight: 10,
    value: {
      item: {
        name: '精铁剑',
        type: ItemType.Weapon,
        description: '精铁打造的利剑，锋利无比',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10 },
      },
    },
  },
  {
    id: 'lottery-weapon-bronze',
    name: '青铜刀',
    type: 'item',
    rarity: '普通',
    weight: 9,
    value: {
      item: {
        name: '青铜刀',
        type: ItemType.Weapon,
        description: '青铜锻造的宝刀，刀锋锐利',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 12 },
      },
    },
  },
  {
    id: 'lottery-weapon-frost',
    name: '青霜剑',
    type: 'item',
    rarity: '稀有',
    weight: 6,
    value: {
      item: {
        name: '青霜剑',
        type: ItemType.Weapon,
        description: '剑身泛着寒光，削铁如泥',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 15 },
      },
    },
  },
  {
    id: 'lottery-weapon-fire',
    name: '烈焰枪',
    type: 'item',
    rarity: '稀有',
    weight: 5,
    value: {
      item: {
        name: '烈焰枪',
        type: ItemType.Weapon,
        description: '枪身燃烧着烈焰，威力惊人',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 18, hp: 20 },
      },
    },
  },
  {
    id: 'lottery-weapon-thunder',
    name: '雷光剑',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '雷光剑',
        type: ItemType.Weapon,
        description: '剑身缠绕着雷光，速度极快',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 20, speed: 10 },
      },
    },
  },
  {
    id: 'lottery-weapon-sky',
    name: '天罡剑',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '天罡剑',
        type: ItemType.Weapon,
        description: '传说中的天罡剑，剑气纵横',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 200, defense: 50 },
      },
    },
  },
  {
    id: 'lottery-weapon-dragon',
    name: '龙吟刀',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '龙吟刀',
        type: ItemType.Weapon,
        description: '刀出如龙吟，威力惊天',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 220, defense: 40, hp: 100 },
      },
    },
  },
  {
    id: 'lottery-weapon-immortal',
    name: '诛仙剑',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '诛仙剑',
        type: ItemType.Weapon,
        description: '传说中的仙剑，可诛仙灭魔',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 3000, defense: 200, hp: 500, spirit: 100 },
      },
    },
  },

  // 普通奖励 - 装备（防具）
  {
    id: 'lottery-armor-cloth',
    name: '布甲',
    type: 'item',
    rarity: '普通',
    weight: 10,
    value: {
      item: {
        name: '布甲',
        type: ItemType.Armor,
        description: '普通的布制护甲，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 5, hp: 20 },
      },
    },
  },
  {
    id: 'lottery-armor-leather',
    name: '皮甲',
    type: 'item',
    rarity: '普通',
    weight: 9,
    value: {
      item: {
        name: '皮甲',
        type: ItemType.Armor,
        description: '用兽皮制作的护甲，比布甲更坚固',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 8, hp: 30 },
      },
    },
  },
  {
    id: 'lottery-armor-cloud',
    name: '云灵道袍',
    type: 'item',
    rarity: '稀有',
    weight: 6,
    value: {
      item: {
        name: '云灵道袍',
        type: ItemType.Armor,
        description: '云灵宗内门弟子道袍，防御力不俗',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 15, hp: 50 },
      },
    },
  },
  {
    id: 'lottery-armor-iron',
    name: '铁甲',
    type: 'item',
    rarity: '稀有',
    weight: 5,
    value: {
      item: {
        name: '铁甲',
        type: ItemType.Armor,
        description: '精铁打造的护甲，防御力强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 20, hp: 60 },
      },
    },
  },
  {
    id: 'lottery-armor-dragon',
    name: '龙鳞甲',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '龙鳞甲',
        type: ItemType.Armor,
        description: '用真龙鳞片打造的护甲，防御力极强',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 150, hp: 500, attack: 30 },
      },
    },
  },
  {
    id: 'lottery-armor-phoenix',
    name: '凤凰羽衣',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '凤凰羽衣',
        type: ItemType.Armor,
        description: '用凤凰羽毛编织的仙衣，轻盈而坚固',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 140, hp: 450, speed: 30, spirit: 40 },
      },
    },
  },
  {
    id: 'lottery-armor-immortal',
    name: '仙灵道袍',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵道袍',
        type: ItemType.Armor,
        description: '仙灵所制的道袍，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 800, hp: 3000, attack: 100, spirit: 200 },
      },
    },
  },

  // 普通奖励 - 装备（饰品）
  {
    id: 'lottery-ring-copper',
    name: '铜戒指',
    type: 'item',
    rarity: '普通',
    weight: 9,
    value: {
      item: {
        name: '铜戒指',
        type: ItemType.Ring,
        description: '普通的铜制戒指，略微提升属性',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 2, defense: 2 },
      },
    },
  },
  {
    id: 'lottery-ring-silver',
    name: '银戒指',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '银戒指',
        type: ItemType.Ring,
        description: '银制的戒指，比铜戒指更精致',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { defense: 5 },
      },
    },
  },
  {
    id: 'lottery-ring-gold',
    name: '金戒指',
    type: 'item',
    rarity: '稀有',
    weight: 5,
    value: {
      item: {
        name: '金戒指',
        type: ItemType.Ring,
        description: '黄金打造的戒指，属性加成不错',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 15, defense: 15 },
      },
    },
  },
  {
    id: 'lottery-ring-star',
    name: '星辰戒指',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰戒指',
        type: ItemType.Ring,
        description: '蕴含星辰之力的戒指，威力强大',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 40, defense: 40, speed: 20 },
      },
    },
  },
  {
    id: 'lottery-ring-daopath',
    name: '大道戒指',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '大道戒指',
        type: ItemType.Ring,
        description: '蕴含大道之力的戒指，威力强大',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 1000, defense: 1000, speed: 1000, spirit: 1000 },
      },
    },
  },
  {
    id: 'lottery-accessory-protect',
    name: '护身符',
    type: 'item',
    rarity: '普通',
    weight: 5,
    value: {
      item: {
        name: '护身符',
        type: ItemType.Accessory,
        description: '普通的护身符，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { defense: 3, hp: 15 },
      },
    },
  },
  {
    id: 'lottery-accessory-jade',
    name: '玉佩',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玉佩',
        type: ItemType.Accessory,
        description: '温润的玉佩，能够静心凝神',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { spirit: 30, hp: 80, defense: 15 },
      },
    },
  },
  {
    id: 'lottery-accessory-immortal',
    name: '仙灵玉佩',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '仙灵玉佩',
        type: ItemType.Accessory,
        description: '仙灵所制的玉佩，蕴含无上仙力',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { attack: 50, defense: 50, hp: 300, spirit: 80 },
      },
    },
  },
  {
    id: 'lottery-accessory-shenpath',
    name: '神道符',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '神道符',
        type: ItemType.Accessory,
        description: '蕴含神道的符箓，据说的得到的人可以窥探天机',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { attack: 2000, defense: 400, hp: 500, spirit: 30000 },
      },
    },
  },

  // 普通奖励 - 法宝
  {
    id: 'lottery-artifact-common-1',
    name: '聚灵珠',
    type: 'item',
    rarity: '普通',
    weight: 6,
    value: {
      item: {
        name: '聚灵珠',
        type: ItemType.Artifact,
        description: '能够聚集天地灵气的宝珠，略微提升修炼速度',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { spirit: 10, exp: 5 },
      },
    },
  },
  {
    id: 'lottery-artifact-common-2',
    name: '护体符',
    type: 'item',
    rarity: '普通',
    weight: 6,
    value: {
      item: {
        name: '护体符',
        type: ItemType.Artifact,
        description: '基础的护身符箓，提供微弱的防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { defense: 10, hp: 30 },
      },
    },
  },
  {
    id: 'lottery-artifact-rare-1',
    name: '玄灵镜',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄灵镜',
        type: ItemType.Artifact,
        description: '能够洞察虚实的宝镜，提升神识和防御',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { spirit: 30, defense: 20 },
      },
    },
  },
  {
    id: 'lottery-artifact-rare-2',
    name: '紫霄钟',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '紫霄钟',
        type: ItemType.Artifact,
        description: '紫霄宫传承法宝，钟声可震慑邪魔',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 100, defense: 50, hp: 200, spirit: 20 },
      },
    },
  },
  {
    id: 'lottery-artifact-rare-3',
    name: '阴阳扇',
    type: 'item',
    rarity: '稀有',
    weight: 3,
    value: {
      item: {
        name: '阴阳扇',
        type: ItemType.Artifact,
        description: '蕴含阴阳之力的宝扇，攻防兼备',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 90, defense: 70, hp: 220 },
      },
    },
  },
  {
    id: 'lottery-artifact-legend-1',
    name: '星辰盘',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰盘',
        type: ItemType.Artifact,
        description: '能够引动星辰之力的法宝，威力无穷',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 50, defense: 50, spirit: 50 },
      },
    },
  },
  {
    id: 'lottery-artifact-legend-2',
    name: '九幽塔',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '九幽塔',
        type: ItemType.Artifact,
        description: '来自九幽之地的宝塔，可镇压一切邪祟',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 500, defense: 300, hp: 1000, spirit: 80 },
      },
    },
  },
  {
    id: 'lottery-artifact-legend-3',
    name: '太虚鼎',
    type: 'item',
    rarity: '传说',
    weight: 1,
    value: {
      item: {
        name: '太虚鼎',
        type: ItemType.Artifact,
        description: '太虚道人的本命法宝，蕴含虚空之力',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 550, defense: 250, hp: 1100, spirit: 120 },
      },
    },
  },
  {
    id: 'lottery-artifact-immortal-1',
    name: '仙灵宝珠',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵宝珠',
        type: ItemType.Artifact,
        description: '仙灵凝聚而成的宝珠，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 150, defense: 150, spirit: 150, hp: 500 },
      },
    },
  },
  {
    id: 'lottery-artifact-immortal-2',
    name: '太极图',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '太极图',
        type: ItemType.Artifact,
        description: '先天至宝，蕴含太极阴阳大道',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 2000, defense: 1000, hp: 5000, spirit: 600 },
      },
    },
  },
  {
    id: 'lottery-artifact-immortal-3',
    name: '混沌印',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '混沌印',
        type: ItemType.Artifact,
        description: '开天辟地时诞生的至宝，可镇压万物',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Artifact1,
        effect: { attack: 2200, defense: 1100, hp: 5500, spirit: 550 },
      },
    },
  },

  // 普通奖励 - 装备（头部）
  {
    id: 'lottery-head-cloth',
    name: '布帽',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '布帽',
        type: ItemType.Armor,
        description: '普通的布制帽子，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Head,
        effect: { defense: 3, hp: 15 },
      },
    },
  },
  {
    id: 'lottery-head-iron',
    name: '铁头盔',
    type: 'item',
    rarity: '普通',
    weight: 7,
    value: {
      item: {
        name: '铁头盔',
        type: ItemType.Armor,
        description: '精铁打造的头盔，防御力不错',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Head,
        effect: { defense: 8, hp: 30 },
      },
    },
  },
  {
    id: 'lottery-head-mystic',
    name: '玄铁头盔',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄铁头盔',
        type: ItemType.Armor,
        description: '玄铁打造的头盔，防御力强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Head,
        effect: { defense: 25, hp: 60, spirit: 10 },
      },
    },
  },
  {
    id: 'lottery-head-star',
    name: '星辰头冠',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰头冠',
        type: ItemType.Armor,
        description: '蕴含星辰之力的头冠，威力强大',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Head,
        effect: { defense: 60, hp: 150, spirit: 20, attack: 10 },
      },
    },
  },
  {
    id: 'lottery-head-immortal',
    name: '仙灵道冠',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵道冠',
        type: ItemType.Armor,
        description: '仙灵所制的道冠，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Head,
        effect: { defense: 150, hp: 400, spirit: 50, attack: 30 },
      },
    },
  },

  // 普通奖励 - 装备（肩部）
  {
    id: 'lottery-shoulder-cloth',
    name: '布肩',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '布肩',
        type: ItemType.Armor,
        description: '普通的布制肩甲，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Shoulder,
        effect: { defense: 3, hp: 15 },
      },
    },
  },
  {
    id: 'lottery-shoulder-iron',
    name: '铁肩甲',
    type: 'item',
    rarity: '普通',
    weight: 7,
    value: {
      item: {
        name: '铁肩甲',
        type: ItemType.Armor,
        description: '精铁打造的肩甲，防御力不错',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Shoulder,
        effect: { defense: 8, hp: 30 },
      },
    },
  },
  {
    id: 'lottery-shoulder-mystic',
    name: '玄铁肩甲',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄铁肩甲',
        type: ItemType.Armor,
        description: '玄铁打造的肩甲，防御力强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Shoulder,
        effect: { defense: 25, hp: 60, spirit: 10 },
      },
    },
  },
  {
    id: 'lottery-shoulder-star',
    name: '星辰云肩',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰云肩',
        type: ItemType.Armor,
        description: '蕴含星辰之力的云肩，威力强大',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Shoulder,
        effect: { defense: 60, hp: 150, spirit: 20, attack: 10 },
      },
    },
  },
  {
    id: 'lottery-shoulder-immortal',
    name: '仙灵云肩',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵云肩',
        type: ItemType.Armor,
        description: '仙灵所制的云肩，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Shoulder,
        effect: { defense: 150, hp: 400, spirit: 50, attack: 30 },
      },
    },
  },

  // 普通奖励 - 装备（手套）
  {
    id: 'lottery-gloves-cloth',
    name: '布手套',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '布手套',
        type: ItemType.Armor,
        description: '普通的布制手套，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Gloves,
        effect: { defense: 3, hp: 15 },
      },
    },
  },
  {
    id: 'lottery-gloves-iron',
    name: '铁护手',
    type: 'item',
    rarity: '普通',
    weight: 7,
    value: {
      item: {
        name: '铁护手',
        type: ItemType.Armor,
        description: '精铁打造的护手，防御力不错',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Gloves,
        effect: { defense: 8, hp: 30 },
      },
    },
  },
  {
    id: 'lottery-gloves-mystic',
    name: '玄铁护手',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄铁护手',
        type: ItemType.Armor,
        description: '玄铁打造的护手，防御力强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Gloves,
        effect: { defense: 25, hp: 60, spirit: 10 },
      },
    },
  },
  {
    id: 'lottery-gloves-star',
    name: '星辰法手',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰法手',
        type: ItemType.Armor,
        description: '蕴含星辰之力的法手，威力强大',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Gloves,
        effect: { defense: 60, hp: 150, spirit: 20, attack: 10 },
      },
    },
  },
  {
    id: 'lottery-gloves-immortal',
    name: '仙灵法手',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵法手',
        type: ItemType.Armor,
        description: '仙灵所制的法手，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Gloves,
        effect: { defense: 150, hp: 400, spirit: 50, attack: 30 },
      },
    },
  },

  // 普通奖励 - 装备（裤腿）
  {
    id: 'lottery-legs-cloth',
    name: '布裤',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '布裤',
        type: ItemType.Armor,
        description: '普通的布制裤子，提供基础防护',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Legs,
        effect: { defense: 4, hp: 18 },
      },
    },
  },
  {
    id: 'lottery-legs-iron',
    name: '铁护腿',
    type: 'item',
    rarity: '普通',
    weight: 7,
    value: {
      item: {
        name: '铁护腿',
        type: ItemType.Armor,
        description: '精铁打造的护腿，防御力不错',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Legs,
        effect: { defense: 10, hp: 40 },
      },
    },
  },
  {
    id: 'lottery-legs-mystic',
    name: '玄铁护腿',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄铁护腿',
        type: ItemType.Armor,
        description: '玄铁打造的护腿，防御力强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Legs,
        effect: { defense: 30, hp: 80 },
      },
    },
  },
  {
    id: 'lottery-legs-star',
    name: '星辰护腿',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰护腿',
        type: ItemType.Armor,
        description: '蕴含星辰之力的护腿，威力强大',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Legs,
        effect: { defense: 75, hp: 200, attack: 15 },
      },
    },
  },
  {
    id: 'lottery-legs-immortal',
    name: '仙灵法裤',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵法裤',
        type: ItemType.Armor,
        description: '仙灵所制的法裤，蕴含无上仙力',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Legs,
        effect: { defense: 180, hp: 500, spirit: 60 },
      },
    },
  },

  // 普通奖励 - 装备（鞋子）
  {
    id: 'lottery-boots-cloth',
    name: '布鞋',
    type: 'item',
    rarity: '普通',
    weight: 8,
    value: {
      item: {
        name: '布鞋',
        type: ItemType.Armor,
        description: '普通的布制鞋子，略微提升速度',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Boots,
        effect: { defense: 3, speed: 2 },
      },
    },
  },
  {
    id: 'lottery-boots-iron',
    name: '铁战靴',
    type: 'item',
    rarity: '普通',
    weight: 7,
    value: {
      item: {
        name: '铁战靴',
        type: ItemType.Armor,
        description: '精铁打造的战靴，防御力和速度都不错',
        quantity: 1,
        rarity: '普通',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Boots,
        effect: { defense: 8, speed: 5 },
      },
    },
  },
  {
    id: 'lottery-boots-mystic',
    name: '玄铁战靴',
    type: 'item',
    rarity: '稀有',
    weight: 4,
    value: {
      item: {
        name: '玄铁战靴',
        type: ItemType.Armor,
        description: '玄铁打造的战靴，防御力和速度强劲',
        quantity: 1,
        rarity: '稀有',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Boots,
        effect: { defense: 25, speed: 12 },
      },
    },
  },
  {
    id: 'lottery-boots-star',
    name: '星辰战靴',
    type: 'item',
    rarity: '传说',
    weight: 2,
    value: {
      item: {
        name: '星辰战靴',
        type: ItemType.Armor,
        description: '蕴含星辰之力的战靴，速度极快',
        quantity: 1,
        rarity: '传说',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Boots,
        effect: { defense: 60, hp: 150, speed: 25 },
      },
    },
  },
  {
    id: 'lottery-boots-immortal',
    name: '仙灵仙履',
    type: 'item',
    rarity: '仙品',
    weight: 1,
    value: {
      item: {
        name: '仙灵仙履',
        type: ItemType.Armor,
        description: '仙灵所制的仙履，蕴含无上仙力，速度惊人',
        quantity: 1,
        rarity: '仙品',
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Boots,
        effect: { defense: 150, hp: 400, speed: 60 },
      },
    },
  },

  // 普通奖励 - 灵宠
  {
    id: 'lottery-pet-fox',
    name: '灵狐',
    type: 'pet',
    rarity: '普通',
    weight: 5,
    value: { petId: 'pet-spirit-fox' },
  },
  {
    id: 'lottery-pet-tiger',
    name: '雷虎',
    type: 'pet',
    rarity: '稀有',
    weight: 3,
    value: { petId: 'pet-thunder-tiger' },
  },
  {
    id: 'lottery-pet-phoenix',
    name: '凤凰',
    type: 'pet',
    rarity: '仙品',
    weight: 1,
    value: { petId: 'pet-phoenix' },
  },

  // 普通奖励 - 抽奖券
  {
    id: 'lottery-ticket-1',
    name: '1张抽奖券',
    type: 'ticket',
    rarity: '普通',
    weight: 15,
    value: { tickets: 1 },
  },
  {
    id: 'lottery-ticket-3',
    name: '3张抽奖券',
    type: 'ticket',
    rarity: '稀有',
    weight: 6,
    value: { tickets: 3 },
  },
  {
    id: 'lottery-ticket-5',
    name: '5张抽奖券',
    type: 'ticket',
    rarity: '传说',
    weight: 2,
    value: { tickets: 5 },
  },
];

// --- 装备模板列表（从抽奖奖品中提取） ---
export const EQUIPMENT_TEMPLATES = LOTTERY_PRIZES.filter(
  (prize) => prize.type === 'item' && prize.value.item?.isEquippable
).map((prize) => {
  const item = prize.value.item!;
  return {
    name: item.name,
    type: item.type,
    rarity: item.rarity || '普通',
    slot: item.equipmentSlot!,
    effect: item.effect,
    description: item.description,
  };
});

// --- 商店系统 ---

export const SHOPS: Shop[] = [
  {
    id: 'shop-village',
    name: '村庄杂货铺',
    type: ShopType.Village,
    description: '小村庄的杂货铺，主要售卖基础物品和低阶材料。',
    items: [
      {
        id: 'shop-herb-1',
        name: '止血草',
        type: ItemType.Herb,
        description: '常见的草药，用于治疗轻微外伤。',
        rarity: '普通',
        price: 10,
        sellPrice: 3,
        effect: { hp: 20 },
      },
      {
        id: 'shop-material-1',
        name: '炼器石',
        type: ItemType.Material,
        description: '用于强化法宝的基础材料。',
        rarity: '普通',
        price: 15,
        sellPrice: 5,
      },
      {
        id: 'shop-pill-1',
        name: '聚气丹',
        type: ItemType.Pill,
        description: '短时间内大幅提升修炼速度。',
        rarity: '普通',
        price: 30,
        sellPrice: 10,
        effect: { exp: 50 },
      },
      {
        id: 'shop-weapon-1',
        name: '木剑',
        type: ItemType.Weapon,
        description: '普通的木制剑，适合初学者。',
        rarity: '普通',
        price: 50,
        sellPrice: 15,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 3 },
      },
    ],
  },
  {
    id: 'shop-city',
    name: '城市商会',
    type: ShopType.City,
    description: '繁华城市的商会，商品种类丰富，品质较高。',
    items: [
      {
        id: 'shop-herb-2',
        name: '聚灵草',
        type: ItemType.Herb,
        description: '吸收天地灵气的草药，炼制聚气丹的主材。',
        rarity: '普通',
        price: 20,
        sellPrice: 7,
      },
      {
        id: 'shop-pill-2',
        name: '回春丹',
        type: ItemType.Pill,
        description: '疗伤圣药，大幅恢复气血。',
        rarity: '稀有',
        price: 100,
        sellPrice: 30,
        effect: { hp: 200 },
      },
      {
        id: 'shop-weapon-2',
        name: '精铁剑',
        type: ItemType.Weapon,
        description: '精铁打造的利剑，锋利无比。',
        rarity: '普通',
        price: 150,
        sellPrice: 45,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10 },
      },
      {
        id: 'shop-armor-1',
        name: '布甲',
        type: ItemType.Armor,
        description: '普通的布制护甲，提供基础防护。',
        rarity: '普通',
        price: 120,
        sellPrice: 36,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 5, hp: 20 },
      },
      {
        id: 'shop-ring-1',
        name: '铜戒指',
        type: ItemType.Ring,
        description: '普通的铜制戒指，略微提升属性。',
        rarity: '普通',
        price: 80,
        sellPrice: 24,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 2, defense: 2 },
      },
    ],
  },
  {
    id: 'shop-sect',
    name: '仙门宝库',
    type: ShopType.Sect,
    description: '仙门内部的宝库，只对门内弟子开放，售卖高阶物品。',
    items: [
      {
        id: 'shop-pill-3',
        name: '洗髓丹',
        type: ItemType.Pill,
        description: '易筋洗髓，脱胎换骨。永久增加少量最大生命值。',
        rarity: '稀有',
        price: 500,
        sellPrice: 150,
        effect: { hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-weapon-3',
        name: '青霜剑',
        type: ItemType.Weapon,
        description: '剑身泛着寒光，削铁如泥。',
        rarity: '稀有',
        price: 800,
        sellPrice: 240,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 15 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-armor-2',
        name: '云灵道袍',
        type: ItemType.Armor,
        description: '云灵宗内门弟子道袍，防御力不俗。',
        rarity: '稀有',
        price: 600,
        sellPrice: 180,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 15, hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-pill-4',
        name: '筑基丹',
        type: ItemType.Pill,
        description: '增加突破到筑基期的几率。服用后获得海量修为。',
        rarity: '传说',
        price: 2000,
        sellPrice: 600,
        effect: { exp: 500 },
        minRealm: RealmType.QiRefining,
      },
      {
        id: 'shop-weapon-legend',
        name: '天罡剑',
        type: ItemType.Weapon,
        description: '传说中的天罡剑，剑气纵横，威力无穷。',
        rarity: '传说',
        price: 5000,
        sellPrice: 1500,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 200, defense: 50 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-armor-legend',
        name: '龙鳞甲',
        type: ItemType.Armor,
        description: '用真龙鳞片打造的护甲，防御力极强。',
        rarity: '传说',
        price: 4000,
        sellPrice: 1200,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 150, hp: 500, attack: 30 },
        minRealm: RealmType.NascentSoul,
      },
      {
        id: 'shop-accessory-1',
        name: '护身符',
        type: ItemType.Accessory,
        description: '普通的护身符，提供基础防护。',
        rarity: '普通',
        price: 1000,
        sellPrice: 300,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { defense: 3, hp: 15 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-weapon-immortal',
        name: '仙剑·诛仙',
        type: ItemType.Weapon,
        description: '传说中的仙剑，一剑可诛仙，威力达到极致。',
        rarity: '仙品',
        price: 20000,
        sellPrice: 6000,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 1000, defense: 200, hp: 500 },
        minRealm: RealmType.SpiritSevering,
      },
      {
        id: 'shop-armor-immortal',
        name: '仙甲·不灭',
        type: ItemType.Armor,
        description: '传说中的仙甲，防御力达到极致，几乎不灭。',
        rarity: '仙品',
        price: 18000,
        sellPrice: 5400,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 800, hp: 2000, attack: 100 },
        minRealm: RealmType.SpiritSevering,
      },
    ],
  },
];
